library(tidyverse)
library(vegan)
library(ggrepel)
library(patchwork)
library(jsonlite)
library(ggridges)
library(patchwork)
library(propagate)
library(pROC)
library(scales)
library(rmarkdown)
library(knitr)
library(renv)

renv::init(bare = TRUE)
renv::hydrate()
renv::snapshot()